### ISSUE TITLE
Hello, can I upgrade the version of Go to 1.20 ?

### ISSUE THREAD

**Issue by rocket2023** [flipped-aurora/gin-vue-admin#1420]
### 功能描述以及必要性描述

can I upgrade the version of Go to 1.20 ?

**Comment by SliverHorn** [comment]
I don't know what you mean.
1. Upgrade go 1.18 in server/go.mod to go 1.20.0. My advice is not to upgrade. The project currently does not use high-version features. If you use the new version of features, you can install the latest version of go 1.18 locally, which means the project supports a minimum of 1.18, because some features require 1.18 or above to run perfectly.
2. It is possible to upgrade the local go version 1.20.0.
