### ISSUE TITLE
设置角色api时报错

### ISSUE THREAD

**Issue by qizhoumeng** [flipped-aurora/gin-vue-admin#178]
设置角色api时报错，前端报:ECONNRESET 错误。
原因是：后台处理时，设置的超时时间目前时10毫秒，这个操作目前需要20秒差不多。临时设置后台读操作时间为30秒。大佬修复一下吧。耗费时间的点主要集中在：`func UpdateCasbin(authorityId string, casbinInfos []request.CasbinInfo) error {
`这个方法。建议操作时批量提交。

**Comment by SliverHorn** [comment]
Hello, this question has many people's feedback about the timeout. Are you using a cloud database? 
If it is a cloud database, it is not recommended to use it during development, and try to use a local database. 
For deployment, it is recommended that the server and cloud database use the intranet, so that it will not time out.

**Comment by qizhoumeng** [comment]
@SliverHorn 哦，是云数据库。
