### ISSUE TITLE
sqlite3 数据库适配和初始数据导入

### ISSUE THREAD

**Issue by ma3315865** [flipped-aurora/gin-vue-admin#407]
### 1. 您使用的是哪个版本的`Go`和系统类型/架构 ?

go version go1.16.2

### 2. 您使用的是哪个版本的 `Nodejs` 和 `npm` 或 `cnpm` ?

v10.16.0

### 3. 您使用的是哪个版本的 `gin-vue-admin` ?

2.4.0

### 4. 可以在master版本中复现此问题吗 ?
可以

### 5. 您做了什么 ?
新版本无法适配sqlite3
原因:
默认依赖版本为casbin3.0.2,在github.com/casbin/gorm-adapter/v3/adapter.go中,官方注释了判断数据库类型为sqlite3的代码.

以下为3.0.2版本代码,注意下面注释了sqlite3判断
func openDBConnection(driverName, dataSourceName string) (*gorm.DB, error) {
	var err error
	var db *gorm.DB
	if driverName == "postgres" {
		db, err = gorm.Open(postgres.Open(dataSourceName+" dbname=postgres"), &gorm.Config{})
	} else if driverName == "mysql" {
		db, err = gorm.Open(mysql.Open(dataSourceName), &gorm.Config{})
	//} else if driverName == "sqlite3" {
	//	db, err = gorm.Open(sqlite.Open(dataSourceName), &gorm.Config{})
	} else if driverName == "sqlserver" {
		db, err = gorm.Open(sqlserver.Open(dataSourceName), &gorm.Config{})
	} else {
		return nil, errors.New("database dialect is not supported")
	}
	if err != nil {
		return nil, err
	}
	return db, err
}

解决办法:
修改config.yaml中system->db-type为sqlite3
升级casbin到最新版.
升级后,在source/authority_menu.go中加入数据库类型sqlite3判断,sql语句中开头修改为CREATE VIEW `authority_menu` AS xxxx,用来创建sqlite3视图.
修改source/casbin.go中所有PType: "p"为Ptype: "p"
然后即可使用initialize/gorm.go中initDB方法用来初始化所需数据

**Comment by hsluoyz** [comment]
@closetool

**Comment by piexlmax** [comment]
您好 非常感谢您的 issue 由于组内人手不足 所以没有太多精力分散去做其他数据库兼容 issue这边会长久保留给其他用户提供参考 非常感谢！

**Comment by closetool** [comment]
@piexlmax @ma3315865 gorm-adapter已经支持了sqlite casbin/gorm-adapter#76

**Comment by hsluoyz** [comment]
@closetool plz make a PR to update the Casbin depends, remove casbin v1.9.1, update casbin and adapter to latest.

https://github.com/flipped-aurora/gin-vue-admin/blob/fd4af6e7ab148c2dfe06d8ec3b2fd4cd1722d71b/server/go.mod#L11-L13

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/flipped-aurora/gin-vue-admin/pull/426

**Comment by hsluoyz** [comment]
@ma3315865

**Comment by SliverHorn** [comment]
@hsluoyz Hello, I'm SliverHorn, the maintainer of [gin-vue-admin](https://github.com/flipped-aurora/gin-vue-admin)，We merge you. [gormadapter](https://github.com/casbin/gorm-adapter) and [casbin](https://github.com/casbin/casbin) `go.mod` Newer version of`pr` #423 ，However, sqlite relies on cgo and many user environments of `gin-vue- admin` do not have `gcc` environment, which makes the project unable to start. After discussion by our team, in order to adapt to more users, In the end, the solution we discussed was that we were , We will use [https://github.com/flipped-aurora/gin-vue-admin/blob/master/server/utils/gormadapter/adapter.go](https://github.com/flipped-aurora/gin-vue-admin/blob/master/server/utils/gormadapter/adapter.go) Code Replace [gormadapter](https://github.com/casbin/gorm-adapter) Warehouse code and keeps Synchronize，Users of [gin-vue-admin](https://github.com/flipped-aurora/gin-vue-admin) open it customized [L227](https://github.com/flipped-aurora/gin-vue-admin/blob/master/server/utils/gormadapter/adapter.go#L227)-[L229](https://github.com/flipped-aurora/gin-vue-admin/blob/master/server/utils/gormadapter/adapter.go#L229) Notes have achieved the effect of supporting sqlite. We have indicated the reason for the change and changed the address in accordance with the Apache agreement and brought their own agreement.

**Comment by hsluoyz** [comment]
@SliverHorn sorry for the inconvenience we caused. We have released Gorm Adaprer v3.2.6 to comment the sqlite and remove cgo: https://github.com/casbin/gorm-adapter/releases/tag/v3.2.6

**Comment by hsluoyz** [comment]
@closetool can you make a PR to replace it back to Gorm Adaprer v3.2.6 and check gin-vue-admin doesn't need cgo?

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/flipped-aurora/gin-vue-admin/pull/432

**Comment by hsluoyz** [comment]
@ma3315865 plz close.
